################################# Default configuration ###################
# provide your domain here
baseURL = "https://examplesite.com/"
# theme
theme = "dot"
# site title
title = "Dot"
# desable language
disableLanguages = []

############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
secondary_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-vimeo-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################# navigation ################################
[[menu.main]]
name = "Faq"
url = "faq"
weight = 1

[[menu.main]]
name = "contact"
url = "contact"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "docs"
hasChildren = true

  [[menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1

  [[menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing"
  weight = 2

  [[menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "The Hugo Documents are copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.en.params.banner]
title = "Support Center & Knowledge base"
description = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact"


################################### Franch Language ######################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
home = "Accueil"
copyright = "Les documents Hugo sont sous copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.fr.params.banner]
title = "Comment pouvons nous aider?"
description = "Trouvez rapidement des conseils et des réponses auprès de notre équipe d'assistance ou contactez-nous."
bg_image = "images/banner.jpg"
placeholder = "Avoir une question? Il suffit de demander ici ou de saisir les termes"

# call to action
[Languages.fr.params.cta]
enable = true
title = "Vous n'avez pas trouvé de réponse à votre question?"
description = "Contactez-nous pour plus de détails sur les services supplémentaires et la tarification du travail personnalisé"
[Languages.fr.params.cta.button]
enable = true
label = "Contactez nous"
link = "contact"